name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: jinnncodes
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check if SVG was generated
        run: |
          echo "Checking SVG output:"
          ls -la dist || (echo "No dist folder!" && exit 1)
          file dist/* || echo "Files not generated"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
