name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution snake animation
        id: generate
        uses: Platane/snk@master
        with:
          github_user_name: jinnncodes
          svg_out_path: dist/github-contribution-grid-snake.svg
          # Optional: gif_out_path: dist/snake.gif

      - name: Check generated files
        run: |
          echo "Checking dist folder"
          ls -la dist || echo "dist folder missing"
          file dist/* || echo "No files found"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
